# Generated by Django 4.2.1 on 2023-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswebsite', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=70)),
                ('small_briff', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='reverse')),
                ('test', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
