# Generated by Django 4.2.1 on 2023-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswebsite', '0005_sliderrepeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='latest/')),
            ],
        ),
        migrations.AlterField(
            model_name='sliderrepeat',
            name='image',
            field=models.ImageField(upload_to='reverse/'),
        ),
    ]
